pub const BEATS: [u8; 4] = [0b1000, 0b0100, 0b0010, 0b0001];

pub const TITLE: [&str; 28] = [
    "0_F#    `",
    "1_G     Tab",
    "2_G#   1",
    "3_A     Q",
    "4_A#   2",
    "5_B     W",
    "6_C     E",
    "7_C#   4",
    "8_D     R",
    "9_D#   5",
    "10_E    T",
    "11_F    Y",
    "12_F#  7",
    "13_G    U",
    "14_G#  8",
    "15_A    I",
    "16_A#  9",
    "17_B    O",
    "18_C    P",
    "19_C#  -",
    "20_D    [",
    "21_D#  =",
    "22_E    ]",
    "23_F   BackSpack",
    "24_F# \\",
    "dummy ",
    "dummy ",
    "dummy ",
];

pub const SYMBOL: [&str; 28] = [
    "minecraft:white_concrete",
    "minecraft:orange_concrete",
    "minecraft:magenta_concrete",
    "minecraft:light_blue_concrete",
    "minecraft:yellow_concrete",
    "minecraft:lime_concrete",
    "minecraft:pink_concrete",
    "minecraft:gray_concrete",
    "minecraft:light_gray_concrete",
    "minecraft:cyan_concrete",
    "minecraft:purple_concrete",
    "minecraft:blue_concrete",
    "minecraft:brown_concrete",
    "minecraft:green_concrete",
    "minecraft:red_concrete",
    "minecraft:black_concrete",
    "minecraft:white_concrete_powder",
    "minecraft:orange_concrete_powder",
    "minecraft:magenta_concrete_powder",
    "minecraft:light_blue_concrete_powder",
    "minecraft:yellow_concrete_powder",
    "minecraft:lime_concrete_powder",
    "minecraft:pink_concrete_powder",
    "minecraft:gray_concrete_powder",
    "minecraft:light_gray_concrete_powder",
    "minecraft:stone",
    "minecraft:birch_fence",
    "minecraft:spruce_fence",
];
pub const TIME_MARK_NAME: [&str; 18] = [
    "0000", "0001", "0010", "0011", "0100", "0101", "0110", "0111", "1000", "1001", "1010", "0011",
    "1100", "1101", "1110", "1111", "dummy", "dummy",
];

pub const TIME_MARK: [&str; 18] = [
    "minecraft:white_carpet",
    "minecraft:orange_carpet",
    "minecraft:magenta_carpet",
    "minecraft:light_blue_carpet",
    "minecraft:yellow_carpet",
    "minecraft:lime_carpet",
    "minecraft:pink_carpet",
    "minecraft:gray_carpet",
    "minecraft:light_gray_carpet",
    "minecraft:cyan_carpet",
    "minecraft:purple_carpet",
    "minecraft:blue_carpet",
    "minecraft:brown_carpet",
    "minecraft:green_carpet",
    "minecraft:red_carpet",
    "minecraft:black_carpet",
    "minecraft:birch_fence",
    "minecraft:spruce_fence",
];

//pub const DUMMY: [&str; 2] = ["minecraft:birch_fence", "minecraft:spruce_fence"];
